name: atomic_webview
description: "Atomic Webview is cross platform webview for android, ios, linux, macos, web, windows"
version: 0.0.8
homepage: https://github.com/Yoda-Man/atomic_webview

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ^3.10.7
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  universal_io: ^2.3.0
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.10
  webview_flutter_web: ^0.2.3+4
  webview_flutter_wkwebview: ^3.23.4    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: AtomicWebviewPlugin
      macos:
        pluginClass: AtomicWebviewPlugin
      windows:
        pluginClass: AtomicWebviewPlugin
