name: atomic_webview
version: 0.1.4
description: "A cross-platform WebView for Android, iOS, macOS, Linux, Windows, and Web, with unified controller support."
homepage: https://github.com/Yoda-Man/atomic_webview
repository: https://github.com/Yoda-Man/atomic_webview

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

environment:
  sdk: ^3.11.5
  flutter: ">=3.41.9"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  universal_io: ^2.3.1
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.12.0
  webview_flutter_web: ^0.2.3+4
  webview_flutter_wkwebview: ^3.25.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: AtomicWebviewPlugin
      macos:
        pluginClass: AtomicWebviewPlugin
      windows:
        pluginClass: AtomicWebviewPlugin
